Repository openshift-knative/backstage-plugins, pull requests merged in 2025-01, with the labels that each got.

#186 [release-v1.15] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#187 [release-v1.16] Update golang.org/x/net to 0.34.0
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved

#196 [release-v1.15] Run `make generate-release`
  openshift/ci-operator/knative-images/eventmesh/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
Labels: approved, lgtm

#194 [main] Update dependabot configurations
  .github/dependabot.yml
  .github/workflows/dependabot-deps.yaml
Labels: needs-ok-to-test

#183 [release-v1.15] Add Konflux configurations
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
  openshift/ci-operator/build-image/Dockerfile
Labels: needs-ok-to-test

#218 [release-v1.16] Update Konflux configurations
  .konflux/applications/serverless-operator-136/serverless-operator-136.yaml
  .konflux/applications/serverless-operator-136/tests/ec-test.yaml
  .konflux/applications/serverless-operator-136/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#217 [release-v1.15] Update Konflux configurations
  .konflux/applications/serverless-operator-135/serverless-operator-135.yaml
  .konflux/applications/serverless-operator-135/tests/ec-test.yaml
  .konflux/applications/serverless-operator-135/tests/override-snapshot-ec-test.yaml
Labels: needs-ok-to-test

#214 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm, needs-ok-to-test
