Repository openshift-knative/backstage-plugins, pull requests merged in 2025-03, with the labels that each got.

#309 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#282 [release-v1.15] Bump to go 1.23
  go.mod
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/eventmesh/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/generate.sh
Labels: approved

#283 [release-v1.16] Bump to go 1.23
  go.mod
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/eventmesh/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
  openshift/generate.sh
Labels: approved

#235 [release-v1.15] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/docker-build.yaml
  .tekton/kn-backstage-plugins-eventmesh-115-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-115-push.yaml
  .tekton/kn-backstage-plugins-migrate-115-pull-request.yaml
  .tekton/kn-backstage-plugins-migrate-115-push.yaml
  .tekton/kn-backstage-plugins-test-eventshub-115-pull-request.yaml
  .tekton/kn-backstage-plugins-test-eventshub-115-push.yaml
Labels: approved, needs-ok-to-test

#240 [release-v1.16] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/kn-backstage-plugins-eventmesh-116-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-116-push.yaml
  .tekton/kn-backstage-plugins-migrate-116-pull-request.yaml
  .tekton/kn-backstage-plugins-migrate-116-push.yaml
  .tekton/kn-backstage-plugins-test-eventshub-116-pull-request.yaml
  .tekton/kn-backstage-plugins-test-eventshub-116-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#310 [release-v1.15] Downgrading to go 1.22
  go.mod
  openshift/ci-operator/build-image/Dockerfile
  openshift/ci-operator/knative-images/eventmesh/Dockerfile
  openshift/ci-operator/knative-images/migrate/Dockerfile
  openshift/ci-operator/knative-test-images/eventshub/Dockerfile
Labels: approved, lgtm

#241 [release-v1.17] Update Konflux configurations
  .github/workflows/dependabot-deps.yaml
  .tekton/kn-backstage-plugins-eventmesh-117-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-117-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#246 [main] Update dependabot configurations
  .github/dependabot.yml
  renovate.json
Labels: approved, lgtm, needs-ok-to-test

#318 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#319 [release-v1.15] Update Konflux configurations
  .tekton/kn-backstage-plugins-eventmesh-115-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-115-push.yaml
  .tekton/kn-backstage-plugins-migrate-115-pull-request.yaml
  .tekton/kn-backstage-plugins-migrate-115-push.yaml
  .tekton/kn-backstage-plugins-test-eventshub-115-pull-request.yaml
  .tekton/kn-backstage-plugins-test-eventshub-115-push.yaml
Labels: approved, lgtm, needs-ok-to-test

#327 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#333 [release-1.17] Upgrade some dependencies
  backstage/package.json
  backstage/yarn.lock
Labels: approved, lgtm

#337 [release-v1.14] Fix 1.14 CVEs
  backstage/package.json
  backstage/yarn.lock
Labels: approved, lgtm

#343 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream

#340 [release-v1.16] Update Konflux configurations
  .tekton/kn-backstage-plugins-eventmesh-116-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-116-push.yaml
  .tekton/kn-backstage-plugins-migrate-116-pull-request.yaml
  .tekton/kn-backstage-plugins-migrate-116-push.yaml
  .tekton/kn-backstage-plugins-test-eventshub-116-pull-request.yaml
  .tekton/kn-backstage-plugins-test-eventshub-116-push.yaml
Labels: approved, lgtm

#346 [main] Update dependabot configurations
  .github/dependabot.yml
Labels: approved, lgtm

#347 [release-v1.15] Update Konflux configurations
  .tekton/docker-build.yaml
Labels: approved, lgtm

#359 [release-v1.15] Pin xml crypto to 2.1.6
  backstage/package.json
  backstage/yarn.lock
Labels: approved, lgtm

#358 Backport https://github.com/knative-extensions/backstage-plugins/pull/181
  backstage/package.json
  backstage/yarn.lock
  openshift/ci-operator/knative-images/eventmesh/Dockerfile
  openshift/generate.sh
Labels: approved, lgtm

#341 [release-v1.17] Update Konflux configurations
  .tekton/kn-backstage-plugins-eventmesh-117-pull-request.yaml
  .tekton/kn-backstage-plugins-eventmesh-117-push.yaml
Labels: approved, lgtm

#376 :robot: Triggering CI on branch 'release-next' after synching to upstream/main
  ci
Labels: approved, lgtm, kind/sync-fork-to-upstream
